@startuml
left to right direction
' Membre
' Conversation 
' Message
' Amitie 

object Membre 
object Amitie
object Groupe


Amitie : dateDebut
Membre : Nom


' Membre "1" --  Membre : ami >
(Membre,Membre) "1" -- "1..5000" Amitie 
Membre "3..*" --  Groupe

@enduml
