@startuml RentIT_Prise_Retour 
actor Client
actor Prepose

participant Systeme 
participant InstitutionFinanciere
participant SAC  


== Prise du véhicule == 
Client -> Prepose : Se présenter au comptoir
Prepose -> Systeme : Identifier la réservation du client  
Prepose -> Systeme : Enregistrer les infos du véhicule  

Prepose -> Client : Demander paiement 
Client -> Prepose : Choisit mode de paiement

alt Paiement en espèces
  Prepose -> Client : Enregistrer paiement   
else Paiement par débit 
  Prepose -> InstitutionFinanciere : Demande autorisation
  InstitutionFinanciere -> Prepose : Autorisation acceptée / refusée 
  Prepose -> Client : Enregistrer paiement 
else Paiement par carte de crédit 
  Prepose -> SAC : Demande autorisation
  SAC -> Prepose : Autorisation acceptée / refusée 
  Prepose -> Client : Enregistrer paiement 
end 
Prepose -> Client : Remettre véhicule 

== Retour du véhicule == 
Client -> Prepose : Retourner véhicule 
Prepose -> Systeme : Enregistrer infos retour 

alt Frais supplémentaires 
  Prepose -> Client : Réclamer frais 
  Prepose -> Systeme : Enregistrer paiement additionnel
end 

@enduml
