@startuml RentIT
left to right direction 
object Membre {
    id
    nom 
    prenom 
    dateNaissance 
    coordonnees
}

object Vehicule {
    immatriculation 
    marque 
    modele 
    kilometrage 
    niveauEssence 
    etat
    disponibilite 
}

object Reservation {
    id
    dateDebut
    dateFin 
    statut 
    frais 
}

object Succursale {
    id
    nom
    adresse 
}

object Employe {
    id
    nom
    role 
}

Membre "1" -- "0..*" Reservation : effectue
Reservation "1" -- "1" Vehicule : concerne
Reservation "1" -- "1" Succursale : a lieu >
Employe "1" -- "0..*" Reservation : gere >
@enduml 
